package actions;

public class ActionsException extends Exception {
	
	// Generated by Eclipse
	private static final long serialVersionUID = 6412261597219869791L;

	public ActionsException(String message) {
		super(message);
	}
	
	public ActionsException(Throwable cause) {
		super(cause);
	}
	
	public ActionsException(String message, Throwable cause) {
		super(message, cause);
	}
}
